### ISSUE TITLE
Error: panic: aws session init failed -- AWS Credentials expired

### ISSUE THREAD

**Issue by sagarrakshe** [one2nc/cloudlens#1]
I installed the tool and launched it. 

```
$ brew install one2nc/cloudlens/cloudlens
$ cloudlens
```

I didn't have a default profile set in `~/.aws/credentials` so I got message
```
Profile 'default' not found, using profile 'personal'...
```

I used `--profile` arg and I got this error
```
Credentials have expired
panic: aws session init failed -- AWS Credentials expired

goroutine 1 [running]:
github.com/one2nc/cloudlens/cmd.run(0x1020e1d00?, {0x10163a704?, 0x0?, 0x0?})
        github.com/one2nc/cloudlens/cmd/root.go:73 +0x4c8
github.com/spf13/cobra.(*Command).execute(0x1020e1d00, {0x14000190200, 0x0, 0x0})
        github.com/spf13/cobra@v1.6.1/command.go:920 +0x5b0
github.com/spf13/cobra.(*Command).ExecuteC(0x1020e1d00)
        github.com/spf13/cobra@v1.6.1/command.go:1044 +0x35c
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.6.1/command.go:968
github.com/one2nc/cloudlens/cmd.Execute()
        github.com/one2nc/cloudlens/cmd/root.go:42 +0x28
main.main()
        github.com/one2nc/cloudlens/main.go:8 +0x1c
```

Same error when I copied the my aws credentials to `default` in ~/.aws/credentials.

### Machine Info
MaC OSX M1 Ventura 13.0

**Comment by chinmay185** [comment]
Thanks for the details @sagarrakshe. We recently changed this behaviour, but on second thoughts, I think we should launch the app, even if the credentials are expired/invalid/not found (instead of panicing).

In the app, we can show a flash message indicating to fix the credentials. We'll fix this soon.

**Comment by sagarrakshe** [comment]
@chinmay185 
Oh! I forgot to mention. My credentials have not expired, I use them daily. Yet I am getting this error.

**Comment by dirien** [comment]
Same for me: I use aws with sso and get all the time this error message. I do a `aws sso login` before starting `cloudlens`

```bash
cloudlens
Profile 'default' not found, using profile 'private'... Credentials have expired
panic: aws session init failed -- AWS Credentials expired

goroutine 1 [running]:
github.com/one2nc/cloudlens/cmd.run(0x10140dd00?, {0x100966704?, 0x0?, 0x0?})
	github.com/one2nc/cloudlens/cmd/root.go:73 +0x4c8
github.com/spf13/cobra.(*Command).execute(0x10140dd00, {0x14000118200, 0x0, 0x0})
	github.com/spf13/cobra@v1.6.1/command.go:920 +0x5b0
github.com/spf13/cobra.(*Command).ExecuteC(0x10140dd00)
	github.com/spf13/cobra@v1.6.1/command.go:1044 +0x35c
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.6.1/command.go:968
github.com/one2nc/cloudlens/cmd.Execute()
	github.com/one2nc/cloudlens/cmd/root.go:42 +0x28
main.main()
	github.com/one2nc/cloudlens/main.go:8 +0x1c
```

**Comment by seh** [comment]
Like @dirien's report in https://github.com/one2nc/cloudlens/issues/1#issuecomment-1457851969, I use [_aws-vault_](https://github.com/99designs/aws-vault) as my credential process, with profiles using SSO.

**Comment by WMRamadan** [comment]
I use MFA with my AWS login and before I login with MFA I would get the following error:

```
Credentials have expired
panic: aws session init failed -- AWS Credentials expired
```

After I login with MFA I get the following error:

```
failed to load AWS SDK config: assume role with MFA enabled, but AssumeRoleTokenProvider session option not set.
```

**Comment by ahuffman** [comment]
similar, but I'm using aws access key is and aws secret access key.  AWS CLI works fine, but I get this from cloudlens:

```
cloudlens
Credentials have expired
panic: aws session init failed -- AWS Credentials expired

goroutine 1 [running]:
github.com/one2nc/cloudlens/cmd.run(0x22f2d20?, {0x1a272af?, 0x0?, 0x0?})
	github.com/one2nc/cloudlens/cmd/root.go:73 +0x4ce
github.com/spf13/cobra.(*Command).execute(0x22f2d20, {0xc00010a200, 0x0, 0x0})
	github.com/spf13/cobra@v1.6.1/command.go:920 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0x22f2d20)
	github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.6.1/command.go:968
github.com/one2nc/cloudlens/cmd.Execute()
	github.com/one2nc/cloudlens/cmd/root.go:42 +0x25
main.main()
	github.com/one2nc/cloudlens/main.go:8 +0x17
```

**Comment by arjunmahishi** [comment]
I think this is the problem: https://github.com/one2nc/cloudlens/blob/d4c437a070500c9804b566ca1fdbb68cee756489/internal/config/config.go#L108-L116

`IsExpired` might not be relevant for all types of authentications. I am using access_token + secret_token, and commenting out this check worked for me

**Comment by golgotow** [comment]
Hi,


installed and getting error like below


```
cloudlens 
Credentials have expired
panic: aws session init failed -- AWS Credentials expired

goroutine 1 [running]:
github.com/one2nc/cloudlens/cmd.run(0x16ede00?, {0xe25ef7?, 0x0?, 0x0?})
	github.com/one2nc/cloudlens/cmd/root.go:73 +0x4ce
github.com/spf13/cobra.(*Command).execute(0x16ede00, {0xc000034240, 0x0, 0x0})
	github.com/spf13/cobra@v1.6.1/command.go:920 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0x16ede00)
	github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.6.1/command.go:968
github.com/one2nc/cloudlens/cmd.Execute()
	github.com/one2nc/cloudlens/cmd/root.go:42 +0x25
main.main()
	github.com/one2nc/cloudlens/main.go:8 +0x17
```


aws command normally work fine for me

Br,

**Comment by marcusschiesser** [comment]
I run into the same issue using [`aws-mfa`](https://github.com/broamski/aws-mfa) with `--assume-role` to authenticate with AWS. I tested with `v0.1.0`.

Here's the output:
```
Credentials have expired
panic: aws session init failed -- AWS Credentials expired

goroutine 1 [running]:
github.com/one2nc/cloudlens/cmd.run(0x123dda0?, {0x970b5a?, 0x0?, 0x0?})
        github.com/one2nc/cloudlens/cmd/root.go:73 +0x4d0
github.com/spf13/cobra.(*Command).execute(0x123dda0, {0x400009e220, 0x0, 0x0})
        github.com/spf13/cobra@v1.6.1/command.go:920 +0x5c8
github.com/spf13/cobra.(*Command).ExecuteC(0x123dda0)
        github.com/spf13/cobra@v1.6.1/command.go:1044 +0x368
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.6.1/command.go:968
github.com/one2nc/cloudlens/cmd.Execute()
        github.com/one2nc/cloudlens/cmd/root.go:42 +0x28
main.main()
        github.com/one2nc/cloudlens/main.go:8 +0x1c
```

**Comment by chinmay185** [comment]
#4 fixes this.
