### ISSUE TITLE
immediate panic when using GCP

### ISSUE THREAD

**Issue by zswanson** [one2nc/cloudlens#45]
Installed with brew, version 0.1.4
First time run, select GCP as the provider. Immediate go panic and crash. Running on Mac M1, Monterey. 
A colleague has the same issue on an Ubuntu VM running on Windows.

```
14:36:19 ❯ cloudlens
panic: runtime error: index out of range [0] with length 0 [recovered]
	panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/derailed/tview.(*Application).Run.func1()
	github.com/derailed/tview@v0.7.2/application.go:243 +0x50
panic({0x101dc8c20, 0x14000198390})
	runtime/panic.go:884 +0x204
github.com/one2nc/cloudlens/internal/view.(*App).handleGCP(0x14000c099a0)
	github.com/one2nc/cloudlens/internal/view/app.go:187 +0x648
github.com/one2nc/cloudlens/internal/view.(*App).handleCloudSelection(0x14000c099a0, {0x101518676?, 0x0?})
	github.com/one2nc/cloudlens/internal/view/app.go:227 +0x9c
github.com/one2nc/cloudlens/internal/view.(*App).showCloudSelectionScreen.func2()
	github.com/one2nc/cloudlens/internal/view/app.go:213 +0x2c
github.com/derailed/tview.(*List).InputHandler.func1(0x14000c7a400?, 0x14000794050?)
	github.com/derailed/tview@v0.7.2/list.go:582 +0xa8
github.com/derailed/tview.(*Box).WrapInputHandler.func1(0x140005e8480?, 0xd4ee60?)
	github.com/derailed/tview@v0.7.2/box.go:182 +0x54
github.com/derailed/tview.(*Flex).InputHandler.func1(0x14000c7a200?, 0x14000794040?)
	github.com/derailed/tview@v0.7.2/flex.go:261 +0xd4
github.com/derailed/tview.(*Box).WrapInputHandler.func1(0x14000c2aae0?, 0x1008ca2ec?)
	github.com/derailed/tview@v0.7.2/box.go:182 +0x54
github.com/derailed/tview.(*Flex).InputHandler.func1(0x140001c1f00?, 0x14000794030?)
	github.com/derailed/tview@v0.7.2/flex.go:261 +0xd4
github.com/derailed/tview.(*Box).WrapInputHandler.func1(0x14000c2a990?, 0x10ac87cc8?)
	github.com/derailed/tview@v0.7.2/box.go:182 +0x54
github.com/derailed/tview.(*Pages).InputHandler.func1(0x10?, 0x101c9a6c0?)
	github.com/derailed/tview@v0.7.2/pages.go:332 +0xa8
github.com/derailed/tview.(*Box).WrapInputHandler.func1(0x14000c2a330?, 0x14000d7fb60?)
	github.com/derailed/tview@v0.7.2/box.go:182 +0x54
github.com/derailed/tview.(*Application).Run(0x140000341c0)
	github.com/derailed/tview@v0.7.2/application.go:334 +0x70c
github.com/one2nc/cloudlens/internal/view.(*App).Run(0x14000c099a0)
	github.com/one2nc/cloudlens/internal/view/app.go:296 +0x80
github.com/one2nc/cloudlens/cmd.initView()
	github.com/one2nc/cloudlens/cmd/root.go:57 +0xd0
github.com/one2nc/cloudlens/cmd.run(0x102d9bbe0?, {0x10151bcb2?, 0x0?, 0x0?})
	github.com/one2nc/cloudlens/cmd/root.go:51 +0x1c
github.com/spf13/cobra.(*Command).execute(0x102d9bbe0, {0x140001901d0, 0x0, 0x0})
	github.com/spf13/cobra@v1.6.1/command.go:920 +0x5b0
github.com/spf13/cobra.(*Command).ExecuteC(0x102d9bbe0)
	github.com/spf13/cobra@v1.6.1/command.go:1044 +0x35c
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.6.1/command.go:968
github.com/one2nc/cloudlens/cmd.Execute()
	github.com/one2nc/cloudlens/cmd/root.go:44 +0x58
main.main()
	github.com/one2nc/cloudlens/main.go:8 +0x1c
```

**Comment by RamanaReddy0M** [comment]
@zswanson, Prior to choosing the provider (AWS/GCP), the application requires the configuration of `GOOGLE_APPLICATION_CREDENTIALS `for GCP or the presence of a `~/.aws/credentials` file for AWS.

Failure to locate the GOOGLE_APPLICATION_CREDENTIALS file or the ~/.aws/credentials file could potentially trigger a panic within the application.

Note: You can also use `cloudlens gcp --cf <cred-file>` cmd for GCP.

**Comment by rupurt** [comment]
Hi @RamanaReddy0M,

I'm also getting the same error after setting the GCP credentials. It looks like it's due to not having permissions to fetch zones https://github.com/one2nc/cloudlens/blob/main/internal/view/app.go#L178C20-L178C30

```
10:15AM DBG Failed to list zones: Get "https://compute.googleapis.com/compute/v1/projects/my-project/zones?alt=json&prettyPrint=false": oauth2: cannot fetch token: 400 Bad Request
Response: {"error":"invalid_grant","error_description":"Invalid JWT Signature."}
```

**Comment by francilioaraujo** [comment]
I'm also getting a panic on debian 12 using aws sso session credentials
```
panic: aws session init failed -- failed to refresh cached credentials, no EC2 IMDS role
 found, operation error ec2imds: GetMetadata, request canceled, context deadline exceede
d [recovered]                                                                           
        panic: aws session init failed -- failed to refresh cached credentials, no EC2 I
MDS role found, operation error ec2imds: GetMetadata, request canceled, context deadline
 exceeded                                                                               
                                                                                        
goroutine 1 [running]:                                                                  
github.com/derailed/tview.(*Application).Run.func1()                                    
        github.com/derailed/tview@v0.7.2/application.go:243 +0x4d                       
panic({0x18457c0, 0xc000be77f0})                                                        
        runtime/panic.go:884 +0x212                                                     
github.com/one2nc/cloudlens/internal/view.(*App).handleAWS(0xc000a19e00)                
        github.com/one2nc/cloudlens/internal/view/app.go:129 +0xa87                    
github.com/one2nc/cloudlens/internal/view.(*App).handleCloudSelection(0xc000a19e00, {0x1
bb5407?, 0x7f9e86af91d8?})
        github.com/one2nc/cloudlens/internal/view/app.go:224 +0x45
github.com/one2nc/cloudlens/internal/view.(*App).showCloudSelectionScreen.func1()
        github.com/one2nc/cloudlens/internal/view/app.go:210 +0x29
github.com/derailed/tview.(*List).InputHandler.func1(0xc000c7f9a0?, 0x9d605f?)
        github.com/derailed/tview@v0.7.2/list.go:582 +0xcf
github.com/derailed/tview.(*Box).WrapInputHandler.func1(0xc00047bb00?, 0xc000c7f9e0?)
        github.com/derailed/tview@v0.7.2/box.go:182 +0x53
github.com/derailed/tview.(*Flex).InputHandler.func1(0xc000c7fa20?, 0x9cdcff?)
        github.com/derailed/tview@v0.7.2/flex.go:261 +0xd9
github.com/derailed/tview.(*Box).WrapInputHandler.func1(0xc000bfe840?, 0xc000c7fa60?)
        github.com/derailed/tview@v0.7.2/box.go:182 +0x53
github.com/derailed/tview.(*Flex).InputHandler.func1(0xc000c7faa0?, 0x9cdcff?)
        github.com/derailed/tview@v0.7.2/flex.go:261 +0xd9
github.com/derailed/tview.(*Box).WrapInputHandler.func1(0xc000bfe6f0?, 0x7f9e86b01a98?)
        github.com/derailed/tview@v0.7.2/box.go:182 +0x53
github.com/derailed/tview.(*Pages).InputHandler.func1(0x40d927?, 0x10?)
        github.com/derailed/tview@v0.7.2/pages.go:332 +0xa7
github.com/derailed/tview.(*Box).WrapInputHandler.func1(0xc000bfe090?, 0xc000c7fba0?)
        github.com/derailed/tview@v0.7.2/box.go:182 +0x53
github.com/derailed/tview.(*Application).Run(0xc00011a1c0)
        github.com/derailed/tview@v0.7.2/application.go:334 +0x75d
github.com/one2nc/cloudlens/internal/view.(*App).Run(0xc000a19e00)
        github.com/one2nc/cloudlens/internal/view/app.go:296 +0x7c
github.com/one2nc/cloudlens/cmd.initView()
        github.com/one2nc/cloudlens/cmd/root.go:57 +0x85
github.com/one2nc/cloudlens/cmd.run(0x2fb7e00?, {0x1bb8c40?, 0x0?, 0x0?})
        github.com/one2nc/cloudlens/cmd/root.go:51 +0x17
github.com/spf13/cobra.(*Command).execute(0x2fb7e00, {0xc00011e1d0, 0x0, 0x0})
        github.com/spf13/cobra@v1.6.1/command.go:920 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0x2fb7e00)
        github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.6.1/command.go:968
github.com/one2nc/cloudlens/cmd.Execute()
        github.com/one2nc/cloudlens/cmd/root.go:44 +0x65
main.main()
        github.com/one2nc/cloudlens/main.go:8 +0x17
```
It seems to try to access IMDS, but I'm using my personal computer

**Comment by francilioaraujo** [comment]
Debugging the code I saw these lines but didn't understand if it should work
https://github.com/one2nc/cloudlens/blob/167bc6b1faef6d41f9ad35d6758ecf6ddb4cb417/internal/view/app.go#L102-L112
I am explicitly setting a profile using the environment variable `AWS_PROFILE` (also `AWS_DEFAULT_PROFILE` and `AWS_EB_PROFILE`), but these lines are setting the default profile nonetheless. What is the point of overwriting the chosen profile?
